// Admin Portal Logic
console.log("!!! ADMIN JS V3.9 LOADED (Fix Form Handlers) !!!");
document.title = "Admin Portal (V3.9)";

// Global handler for item clicks to avoid inline JS issues


let ADMIN_USERS = [];
let GEMINI_API_KEYS = []; // Array for rotation

async function loadGeminiCredentials() {
    try {
        const response = await fetch('geminiCredintials.txt?v=' + Date.now());
        if (!response.ok) throw new Error("Failed to load Gemini credentials");
        const text = await response.text();
        const lines = text.split(/\r?\n/);

        GEMINI_API_KEYS = []; // Reset
        for (const line of lines) {
            if (line.toLowerCase().includes('gemini api key:')) {
                const key = line.split(/gemini api key:/i)[1].trim();
                if (key) GEMINI_API_KEYS.push(key);
            }
        }
        console.log(`Admin: Loaded ${GEMINI_API_KEYS.length} Gemini keys.`);
    } catch (e) {
        console.error("Admin: Failed to load Gemini credentials", e);
    }
}

// --- AI Product Analysis ---
async function analyzeImageWithGemini(file) {
    console.log("Admin: analyzeImageWithGemini called");

    // Retry loading keys if missing
    if (GEMINI_API_KEYS.length === 0) {
        console.warn("Gemini Keys missing, reloading...");
        await loadGeminiCredentials();
    }

    if (GEMINI_API_KEYS.length === 0) {
        alert("System Error: No Gemini API Keys found. Check geminiCredintials.txt");
        return;
    }

    const label = document.querySelector('label[for="product-image-upload"]');
    const originalText = "Product Image";

    // UI Loading State
    if (label) {
        label.innerHTML = 'Product Image <div class="ai-spinner"></div> <span style="margin-left:10px; color:var(--accent); font-size:0.9em;">Analyzing with Gemini AI...</span>';
    }

    const loadingText = "Generated by AI... ⏳";
    const inputsToReset = [
        'input[name="product name"]',
        'input[name="Arabic Name"]',
        'textarea[name="description (80 word)"]',
        'input[name="category"]',
        'input[name="collection"]',
        'input[name="target market"]'
    ];

    inputsToReset.forEach(selector => {
        const el = document.querySelector(selector);
        if (el) el.value = loadingText;
    });

    try {
        console.log("Admin: Reading image...");
        const reader = new FileReader();
        reader.readAsDataURL(file);

        reader.onloadend = async () => {
            const base64Data = reader.result.split(',')[1];
            const mimeType = file.type;

            const prompt = `You are a product management assistant. Analyze the image and provide the following 6 details.
1. Promotional Name (English - short, functional, catchy)
2. Promotional Name (Arabic - short, functional, catchy - translated/adapted from English)
3. Description (English - 80 words max, compelling)
4. Category (Must be: "Home Decor & Organization - Desk Accessories" if relevant, or the closest matching category)
5. Collection Name (Creative and relevant)
6. Target Market (e.g., "Office Works", "Gamers", "Students")

CRITICAL OUTPUT FORMAT:
Return ONLY the values separated by "|||".
DO NOT include labels like "Name:" or "Description:".
DO NOT use markdown formatting.
Example:
Super Desk Organizer ||| منظم مكتب سوبر ||| Keep your desk tidy... ||| Home Decor & Organization - Desk Accessories ||| Office Zen ||| Professionals`;

            const payload = {
                contents: [{
                    parts: [
                        { text: prompt },
                        {
                            inline_data: {
                                mime_type: mimeType,
                                data: base64Data
                            }
                        }
                    ]
                }]
            };

            let success = false;
            let lastError = null;

            // Try keys sequentially
            for (let i = 0; i < GEMINI_API_KEYS.length; i++) {
                const apiKey = GEMINI_API_KEYS[i];
                const controller = new AbortController();
                const timeoutId = setTimeout(() => controller.abort(), 25000); // 25s Timeout

                try {
                    console.log(`Admin: Requesting Gemini with key index ${i}...`);
                    // Use exact model string from chatbot.js (gemini-flash-latest) which is known to work
                    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key=${apiKey}`, {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/json' },
                        body: JSON.stringify(payload),
                        signal: controller.signal
                    });
                    clearTimeout(timeoutId);

                    const data = await response.json();

                    if (data.error) {
                        console.warn(`Key ${i} failed:`, data.error.message);
                        throw new Error(data.error.message);
                    }

                    if (data.candidates && data.candidates[0].content) {
                        const text = data.candidates[0].content.parts[0].text;
                        console.log("AI Response:", text);

                        const parts = text.split('|||').map(p => p.trim());

                        if (parts[0]) document.querySelector('input[name="product name"]').value = parts[0];
                        if (parts[1]) document.querySelector('input[name="Arabic Name"]').value = parts[1];
                        if (parts[2]) document.querySelector('textarea[name="description (80 word)"]').value = parts[2];
                        if (parts[3]) document.querySelector('input[name="category"]').value = parts[3];
                        if (parts[4]) document.querySelector('input[name="collection"]').value = parts[4];
                        if (parts[5]) document.querySelector('input[name="target market"]').value = parts[5];

                        if (label) {
                            label.innerHTML = 'Product Image <span style="margin-left:5px; color:#10b981;">Analysis Complete! ✨</span>';
                            setTimeout(() => {
                                label.textContent = originalText;
                                label.style.color = "inherit";
                            }, 5000);
                        }

                        success = true;
                        break; // Exit loop on success
                    }

                } catch (err) {
                    lastError = err;
                    console.error(`Attempt ${i} failed:`, err);
                }
            }

            if (!success) {
                console.error("All Gemini keys failed.");
                const errorMsg = lastError ? lastError.message : "Connection/Quota Error";
                // alert(`AI Analysis Failed: ${errorMsg}`); // Alert is annoying if it happens often, maybe just show in fields

                // Show error in fields so user knows why it disappeared
                const failureText = "⚠️ Generation Failed. Try again.";
                inputsToReset.forEach(selector => {
                    const el = document.querySelector(selector);
                    if (el && el.value === loadingText) {
                        el.value = failureText;
                        el.title = errorMsg; // Tooltip for debug
                    }
                });

                if (label) {
                    label.innerHTML = 'Product Image <span style="margin-left:5px; color:#ef4444;">AI Failed ❌</span>';
                }
            }
        };

    } catch (e) {
        console.error("AI Analysis Critical Error:", e);
        if (label) label.textContent = "Product Image (Error)";
        alert("Error: " + e.message);
    }
}
async function loadCredentials() {
    try {
        // Add cache busting to ensure we get the latest file content
        const response = await fetch('adminCredentials.txt?v=' + new Date().getTime());
        if (!response.ok) throw new Error("Failed to load credentials");
        const text = await response.text();
        const lines = text.split(/\r?\n/);

        ADMIN_USERS = []; // Clear existing
        let currentUser = {};

        for (const line of lines) {
            const trimmed = line.trim();
            if (!trimmed) {
                // Empty line acts as delimiter/commit for previous user
                if (currentUser.email && currentUser.pass) {
                    ADMIN_USERS.push(currentUser);
                    currentUser = {};
                }
                continue;
            }

            // Robust parsing: Split only on first colon to support passwords with colons
            const firstColon = line.indexOf(':');
            if (firstColon === -1) continue;

            const key = line.substring(0, firstColon).trim().toLowerCase(); // Normalize key
            const value = line.substring(firstColon + 1).trim();

            if (key === 'username') {
                // If starting a new user block without an empty line separator
                if (currentUser.email && currentUser.pass) {
                    ADMIN_USERS.push(currentUser);
                    currentUser = {};
                }
                currentUser.email = value.toLowerCase();
            } else if (key === 'password') {
                currentUser.pass = value;
            }
        }

        // Push the final user if exists
        if (currentUser.email && currentUser.pass) {
            ADMIN_USERS.push(currentUser);
        }

        console.log(`Admin: Loaded ${ADMIN_USERS.length} users.`);

    } catch (e) {
        console.error("Admin: Could not load credentials", e);
    }

    // Emergency Fallback User (added by system)
    if (ADMIN_USERS.length === 0) {
        console.warn("Admin: Using fallback credentials due to load failure.");
        ADMIN_USERS.push({ email: 'admin', pass: 'admin123' });
    }
}


document.addEventListener('DOMContentLoaded', async () => {
    // 1. Attach Login Listener Immediately (Fix Vercel Race Condition)
    const loginForm = document.getElementById('login-form');
    const loginBtn = document.querySelector('.btn-primary');

    const handleLogin = (e) => {
        if (e) {
            e.preventDefault();
            e.stopPropagation();
        }

        if (ADMIN_USERS.length === 0) {
            alert("System initializing... please wait.");
            return;
        }

        const emailInput = document.getElementById('admin-email');
        const passInput = document.getElementById('admin-password');
        if (!emailInput || !passInput) return;

        const email = emailInput.value;
        const pass = passInput.value;
        const err = document.getElementById('login-error');

        const validUser = ADMIN_USERS.find(u =>
            u.email === email.trim().toLowerCase() && u.pass === pass.trim()
        );

        if (validUser) {
            sessionStorage.setItem('admin_logged_in', 'true');
            if (err) err.classList.add('hidden');
            showDashboard();
        } else {
            console.warn("Admin: Login Failed");
            if (err) err.classList.remove('hidden');
        }
    };

    if (loginForm) {
        loginForm.addEventListener('submit', handleLogin);
    }
    if (loginBtn) {
        // Double safety for Vercel race conditions / structural issues
        loginBtn.addEventListener('click', (e) => {
            // Only if it's not a submit button (which it is) but preventing default just in case
            // actually if it is submit, the form submit fires.
            // But if form is broken, catching click helps.
            if (loginBtn.type !== 'submit') handleLogin(e);
        });
    }
    await loadCredentials();
    await loadGeminiCredentials();

    // Check Session
    if (sessionStorage.getItem('admin_logged_in') === 'true') {
        showDashboard();
    } else {
        showLogin();
    }

    // Initialize Icons
    if (window.lucide) lucide.createIcons();

    // Attach Image Upload Analysis Listener
    const imgInput = document.getElementById('product-image-upload');
    if (imgInput) {
        console.log("Admin: Event listener attached to #product-image-upload");
        imgInput.addEventListener('change', async (e) => {
            console.log("Admin: Image file selected/changed");
            if (e.target.files && e.target.files[0]) {
                await analyzeImageWithGemini(e.target.files[0]);
            }
        });
    }



    // Navigation Handler
    document.querySelectorAll('.nav-item[data-view]').forEach(btn => {
        btn.addEventListener('click', () => {
            // Update Active State
            document.querySelectorAll('.nav-item').forEach(b => b.classList.remove('active'));
            btn.classList.add('active');

            // Show View
            const viewId = `view-${btn.dataset.view}`;
            document.querySelectorAll('.view-section').forEach(v => v.classList.add('hidden'));
            document.getElementById(viewId).classList.remove('hidden');
            document.getElementById('page-title').textContent = btn.textContent.trim();
            if (btn.dataset.view === 'products') {
                loadProducts();
            } else if (btn.dataset.view === 'add-product') {
                prepareAddProductForm();
            } else if (btn.dataset.view === 'create-order') {
                initCreateOrder();
            } else if (btn.dataset.view === 'social-generator') {
                initSocialGenerator();
            } else if (btn.dataset.view === 'upload-images') {
                initUploadImages();
            }
        });
    });

    // Logout
    document.getElementById('logout-btn').addEventListener('click', () => {
        sessionStorage.removeItem('admin_logged_in');
        window.location.reload();
    });

    document.getElementById('refresh-products-btn')?.addEventListener('click', loadProducts);

    // Add Product Form Handler
    const addProductForm = document.getElementById('add-product-form');
    if (addProductForm) {
        addProductForm.addEventListener('submit', async (e) => {
            e.preventDefault();
            const msg = document.getElementById('add-product-msg');
            const err = document.getElementById('add-product-error');
            msg.classList.add('hidden');
            err.classList.add('hidden');

            const form = e.target;
            const formData = new FormData(form);
            const data = Object.fromEntries(formData.entries());

            const no = data['No'].trim();
            if (!no) {
                err.textContent = "Item Number is required";
                err.classList.remove('hidden');
                return;
            }

            // 1. Validate GAS URL
            const gasUrl = document.getElementById('google-script-url').value.trim();
            if (!gasUrl) {
                err.textContent = "Please provide the Google Apps Script URL.";
                err.classList.remove('hidden');
                return;
            }

            const submitBtn = form.querySelector('button[type="submit"]');
            const originalBtnText = submitBtn.innerText;

            // Show loading
            const loading = document.getElementById('loading-modal');
            loading.classList.remove('hidden');
            submitBtn.disabled = true;
            submitBtn.innerText = "Processing...";

            // 2. Prepare Data for GAS
            const action = document.getElementById('product-action').value || 'addProduct';
            const gasData = {
                'action': action,
                'No': no,
                'Name on Store': data['Name on Store'],
                'product name': data['product name'],
                'Arabic Name': data['Arabic Name'],
                'category': data['category'],
                'collection': data['collection'],
                'description (80 word)': data['description (80 word)'],
                'Dimensions(mm) x y z': data['Dimensions(mm) x y z'],
                'Colors': data['Colors'],
                'Price < 25 QTY': data['Price < 25 QTY'],
                'target market': data['target market'],
                'Document Link': data['Document Link'],
                'Calculate on Weight': data['Calculate on Weight'],
                'Price >= 25 QTY': data['Price >=25 QTY'], // Standardize key to "Price >= 25 QTY" (with spaces)

                'Available': form.querySelector('[name="Available"]').checked ? "TRUE" : "FALSE",
                'Hidden': form.querySelector('[name="Hidden"]').checked ? "TRUE" : "FALSE",
                'Active': form.querySelector('[name="Active"]').checked ? "TRUE" : "FALSE",
            };

            // 3. Handle Image (Convert to Base64)
            const fileInput = document.getElementById('product-image-upload');
            if (fileInput && fileInput.files.length > 0) {
                const file = fileInput.files[0];
                const reader = new FileReader();

                reader.onerror = function () {
                    console.error("FileReader error");
                    loading.classList.add('hidden');
                    submitBtn.disabled = false;
                    submitBtn.innerText = originalBtnText;
                    err.textContent = "Failed to read file";
                    err.classList.remove('hidden');
                };

                reader.onload = async function (e) {
                    const base64 = e.target.result.split(',')[1]; // Remove data:image/...;base64,
                    gasData.image = base64;
                    const ext = file.name.split('.').pop();
                    const newFileName = `${no}.${ext}`;
                    gasData.imageName = newFileName; // Rename to ItemNo.ext
                    gasData.mimeType = file.type;

                    // --- LOCAL UPLOAD ---
                    try {
                        console.log("Uploading image locally...");
                        const localRes = await fetch('/api/upload-image', {
                            method: 'POST',
                            body: file, // Send raw part
                            headers: {
                                'X-Filename': newFileName
                            }
                        });
                        if (localRes.ok) {
                            console.log("Local upload success");
                        } else {
                            console.error("Local upload failed");
                        }
                    } catch (uploadErr) {
                        console.error("Local upload error", uploadErr);
                    }
                    // --------------------

                    submitToGas(gasUrl, gasData);
                };

                reader.readAsDataURL(file);
            } else {
                submitToGas(gasUrl, gasData);
            }

            window.submitToGas = submitToGas;
            async function submitToGas(url, payload) {
                try {
                    // Use 'no-cors' if GAS doesn't return CORS headers, handle blindly?
                    // GAS Web Apps usually return simple JSON if configured right.
                    // But standard fetch might fail CORS if not handled in GAS with `ContentService`.
                    // My GAS code uses `ContentService` which generally works with redirects.

                    // Actually, Fetching GAS Web App often requires `redirect: 'follow'`.
                    // But doing it from browser often hits CORS.
                    // The best way is using `no-cors` for fire-and-forget OR fetch with `application/x-www-form-urlencoded` text/plain to avoid preflight?
                    // POSTing JSON usually triggers preflight which GAS doesn't support.
                    // So we must use `text/plain` for the body type to avoid preflight!

                    console.log("[DEBUG] Submitting to GAS. URL:", url);
                    console.log("[DEBUG] Payload:", JSON.stringify(payload, null, 2));

                    const res = await fetch(url, {
                        method: 'POST',
                        body: JSON.stringify(payload),
                        headers: {
                            "Content-Type": "text/plain;charset=utf-8", // Hacks to avoid preflight
                        },
                    });

                    const text = await res.text();
                    let json = {};
                    try {
                        json = JSON.parse(text);
                    } catch (e) {
                        // If opaque, assume success?
                        console.warn("Could not parse GAS response", text);
                    }

                    if (json.result === 'success') {
                        msg.textContent = "Product sent! Redirecting to Social Generator... 🚀";
                        msg.classList.remove('hidden');

                        // Wait a moment for UX
                        setTimeout(async () => {
                            form.reset();
                            msg.classList.add('hidden');

                            // 1. Switch View
                            document.querySelectorAll('.view-section').forEach(v => v.classList.add('hidden'));
                            document.getElementById('view-social-generator').classList.remove('hidden');

                            // 2. Update Nav
                            document.querySelectorAll('.nav-item').forEach(b => b.classList.remove('active'));
                            document.querySelector('.nav-item[data-view="social-generator"]')?.classList.add('active');

                            // 3. Init Generator (ensure dropdown is ready if needed, though we bypass selection)
                            if (window.initSocialGenerator) await window.initSocialGenerator();

                            // 4. Update Dropdown to match new item (Visual only)
                            const select = document.getElementById('social-product-select');
                            if (select) {
                                // Add option if not exists (Optimistic update)
                                const exists = [...select.options].some(o => o.value === payload.No);
                                if (!exists) {
                                    const opt = document.createElement('option');
                                    opt.value = payload.No;
                                    opt.textContent = `${payload.No} - ${payload['product name'] || payload['Name on Store'] || 'New Product'}`;
                                    select.appendChild(opt);
                                }
                                select.value = payload.No;
                            }

                            // 5. Trigger Generation
                            // Map payload keys to what generateSocialPost expects if needed, or just pass payload
                            // payload keys: 'Name on Store', 'product name', 'Dimensions(mm) x y z', 'Price < 25 QTY', 'Document Link'
                            // generateSocialPost keys: check function
                            if (typeof generateSocialPost === 'function') {
                                await generateSocialPost(payload);
                            }

                        }, 1000);

                    } else {
                        throw new Error(json.error || ("Request failed (Status: " + res.status + "). Check permissions (Should be 'Anyone')."));
                    }
                } catch (ex) {
                    console.error(ex);
                    err.textContent = "Failed to sync with Google Sheet: " + ex.message;
                    err.classList.remove('hidden');
                } finally {
                    loading.classList.add('hidden');
                    submitBtn.disabled = false;
                    submitBtn.innerText = originalBtnText;
                }
            }
        });

        // Price Calculation Logic
        const weightInput = addProductForm.querySelector('input[name="Calculate on Weight"]');
        if (weightInput) {
            weightInput.addEventListener('blur', (e) => {
                const weight = parseFloat(e.target.value);
                if (isNaN(weight)) return;

                // Price < 25 QTY Logic
                // =IF(Weight<35, Weight*0.075, IF(Weight<60, Weight*0.06, IF(Weight<150, Weight*0.05, Weight*0.04)))
                let priceSmall = 0;
                if (weight < 35) priceSmall = weight * 0.075;
                else if (weight < 60) priceSmall = weight * 0.06;
                else if (weight < 150) priceSmall = weight * 0.05;
                else priceSmall = weight * 0.04;

                // Wholesale Price (>= 25 QTY) Logic
                // =IF(Weight<35, Weight*0.06, IF(Weight<150, Weight*0.05, Weight*0.04))
                let priceWholesale = 0;
                if (weight < 35) priceWholesale = weight * 0.06;
                else if (weight < 150) priceWholesale = weight * 0.05;
                else priceWholesale = weight * 0.04;

                // Update Fields (rounding to 3 decimals)
                const priceSmallInput = addProductForm.querySelector('input[name="Price < 25 QTY"]');
                const priceWholesaleInput = addProductForm.querySelector('input[name="Price >=25 QTY"]');

                if (priceSmallInput) priceSmallInput.value = priceSmall.toFixed(3);
                if (priceWholesaleInput) priceWholesaleInput.value = priceWholesale.toFixed(3);

                console.log(`Calculated Prices for Weight ${weight}: <25=${priceSmall}, >=25=${priceWholesale}`);
            });
        }
    }



    // Settings Handler
    const saveSettingsBtn = document.getElementById('save-settings-btn');
    if (saveSettingsBtn) {
        // Load initial settings
        loadSettings();

        saveSettingsBtn.addEventListener('click', async () => {
            const enabled = document.getElementById('email-enabled').checked;
            const receiver = document.getElementById('receiver-email').value.trim();
            const sender = document.getElementById('sender-email').value.trim();
            const pass = document.getElementById('sender-pass').value.trim();
            const msg = document.getElementById('settings-msg');

            try {
                const res = await fetch('/api/settings', {
                    method: 'POST',
                    body: JSON.stringify({
                        enabled: enabled,
                        receiver_email: receiver,
                        sender_email: sender,
                        sender_pass: pass
                    })
                });

                const json = await res.json();
                if (json.status === 'success') {
                    msg.textContent = "Settings saved successfully!";
                    msg.classList.remove('hidden');
                    setTimeout(() => msg.classList.add('hidden'), 3000);
                } else {
                    alert("Failed: " + json.error);
                }
            } catch (e) {
                alert("Error saving settings: " + e.message);
            }
        });
    }

    async function loadSettings() {
        try {
            const res = await fetch('/api/settings');
            const config = await res.json();
            if (config.enabled !== undefined) {
                document.getElementById('email-enabled').checked = config.enabled;
                document.getElementById('receiver-email').value = config.receiver_email || '';
                document.getElementById('sender-email').value = config.sender_email || '';
                document.getElementById('sender-pass').value = config.sender_pass || '';
            }
        } catch (e) {
            console.error("Failed to load settings", e);
        }
    }

    // Delegated Event Listener for Order Item Tiles
    const ordersBody = document.getElementById('orders-table-body');
    if (ordersBody) {
        console.log("Attaching event listener to orders-table-body");
        ordersBody.addEventListener('click', (e) => {
            console.log("Click detected on orders body. Target:", e.target);
            const tile = e.target.closest('.item-tile');
            if (tile) {
                // Prevent row toggle or other side effects
                e.preventDefault();
                e.stopPropagation();

                const sku = tile.dataset.sku;
                console.log("Delegated Click on Tile. SKU:", sku);

                if (sku) {
                    console.log("Attempting to expand item:", sku);
                    window.toggleItemExpansion(tile, sku);
                } else {
                    console.warn("Tile clicked but no SKU found in dataset");
                }
            }
        });
    } else {
        console.error("CRITICAL: orders-table-body not found during initialization");
    }
});


// --- Social Media Generator ---
window.initSocialGenerator = async function () {
    console.log("Initializing Social Generator...");
    const select = document.getElementById('social-product-select');
    const btn = document.getElementById('generate-social-btn');

    if (!select || !btn) return;

    // Load products if not loaded
    let products = window.productsData;
    if (!products || products.length === 0) {
        try {
            products = await window.fetchProductsData();
        } catch (e) { console.error("Error loading products for social", e); return; }
    }

    // Populate Dropdown
    select.innerHTML = '<option value="">-- Choose a Product --</option>';
    // Sort logic? maybe newest first.
    products.forEach(p => {
        if (!p['No']) return;
        const name = p['Name on Store'] || p['product name'] || p['Product Name'] || 'Unknown Name';
        const option = document.createElement('option');
        option.value = p['No'];
        option.textContent = `${p['No']} - ${name}`;
        select.appendChild(option);
    });

    // Remove old listeners to avoid duplicates if re-init
    const newBtn = btn.cloneNode(true);
    btn.parentNode.replaceChild(newBtn, btn);

    newBtn.addEventListener('click', async () => {
        const sku = select.value;
        if (!sku) { alert("Please select a product first."); return; }

        const product = products.find(p => p['No'] === sku);
        if (!product) return;

        await generateSocialPost(product);
    });
};

async function generateSocialPost(product) {
    const output = document.getElementById('social-post-output');
    const btn = document.getElementById('generate-social-btn');

    if (GEMINI_API_KEYS.length === 0) {
        await loadGeminiCredentials();
        if (GEMINI_API_KEYS.length === 0) {
            output.value = "Error: Gemini API Keys not found.";
            return;
        }
    }

    const originalText = btn.innerHTML;
    btn.disabled = true;
    btn.innerHTML = '<span>Generating... ⏳</span>';
    output.value = "AI is writing your post... please wait.";

    try {
        const name = product['Name on Store'] || product['product name'] || product['Product Name'] || 'Unknown Product';
        const dimensions = product['Dimensions(mm) x y z'] || product['Dimensions'] || 'N/A';
        const price = product['Price < 25 QTY'] || product['Price'] || product['Retail Price'] || 'N/A';
        const link = product['Document Link'] || product['link'] || '';

        const prompt = `Act as a professional social media manager and copywriter for a brand called "Creative Rarities" that sells 3D printed products for home organization, aquariums, and pets.
        
        Product Details:
        - Name: ${name}
        - Dimensions: ${dimensions}
        - Price: ${price} JOD
        - Link: ${link}

        Your task is to write a social media post caption (in colloquial Arabic/Ammiya) following this exact structure:
        
        Hook: Start with a catchy question or a fun statement that addresses a problem the product solves. use emojis.
        Description: Briefly explain what the product is and why it's cool/useful in a friendly, engaging tone. Mention if it has a specific design feature.
        
        Details Block: List the dimensions and price clearly using this format:
        📏 الأبعاد: [Insert Dimensions] mm
        💰 السعر: [Insert Price] JOD
        
        Call to Action: Tell them to find it in the bio link by searching for its English name. Use this exact phrasing:
        "عشان تطلبوه وتلاقوه بالقائمة (الرابط بالبايو)، دوروا على اسمه بالإنجليزي: ${name}"
        
        Link: Add the provided Google Drive link with the text if provided:
        🔗 رابط التفاصيل:
        ${link ? link : "[Link not provided]"}
        
        Hashtags: Add 4-5 relevant hashtags in Arabic and English (e.g., #Aquarium #Decor #CatToys) and always add the hashtag #crtv_rarities.
        
        Important Notes:
        Keep the tone friendly, enthusiastic, and helpful.
        The description should be in one single column/block.
        Do not translate the Product Name in the "Call to Action" section.
        Return ONLY the post content.`;

        const payload = {
            contents: [{ parts: [{ text: prompt }] }]
        };

        // Reuse Gemini fetch logic simpler here
        let success = false;
        for (const apiKey of GEMINI_API_KEYS) {
            try {
                const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key=${apiKey}`, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify(payload)
                });
                const data = await response.json();
                if (data.candidates && data.candidates[0].content) {
                    output.value = data.candidates[0].content.parts[0].text;
                    success = true;
                    break;
                }
            } catch (e) { console.error("Key failed", e); }
        }

        if (!success) {
            output.value = "Failed to generate post. Please check API keys or connection.";
        }

    } catch (e) {
        console.error("Generation error", e);
        output.value = "Error: " + e.message;
    } finally {
        btn.disabled = false;
        btn.innerHTML = originalText;
    }
}


// --- Upload Extra Images ---
window.initUploadImages = async function () {
    console.log("Initializing Upload Images...");
    const select = document.getElementById('upload-product-select');
    const btn = document.getElementById('upload-images-btn');
    const input = document.getElementById('extra-images-input');
    const status = document.getElementById('upload-status');

    if (!select || !btn) return;

    // Load products if not loaded
    let products = window.productsData;
    if (!products || products.length === 0) {
        try {
            products = await window.fetchProductsData();
        } catch (e) { console.error("Error loading products for upload", e); return; }
    }

    // Populate Dropdown
    select.innerHTML = '<option value="">-- Choose a Product --</option>';
    products.forEach(p => {
        if (!p['No']) return;
        const name = p['Name on Store'] || p['product name'] || p['Product Name'] || 'Unknown Name';
        const option = document.createElement('option');
        option.value = p['No'];
        option.textContent = `${p['No']} - ${name}`;
        select.appendChild(option);
    });

    // Remove old listeners
    const newBtn = btn.cloneNode(true);
    btn.parentNode.replaceChild(newBtn, btn);

    newBtn.addEventListener('click', async () => {
        const productNo = select.value;
        const files = input.files;

        if (!productNo) { alert("Please select a product."); return; }
        if (files.length === 0) { alert("Please select at least one image."); return; }

        newBtn.disabled = true;
        newBtn.innerHTML = '<span>Uploading... ⏳</span>';
        status.textContent = "";
        status.style.color = "var(--text-secondary)";

        const formData = new FormData();
        formData.append('productNo', productNo);
        for (let i = 0; i < files.length; i++) {
            formData.append('images', files[i]);
        }

        try {
            // Handle file deployment vs server deployment
            const isLocalFile = window.location.protocol === 'file:';
            const apiBase = isLocalFile ? 'http://localhost:8000' : '';

            const res = await fetch(`${apiBase}/api/upload-images`, {
                method: 'POST',
                body: formData
            });

            const json = await res.json();

            if (res.ok && json.status === 'success') {
                status.textContent = "✅ " + json.message;
                status.style.color = "#34d399";
                input.value = ""; // Clear selection
            } else {
                throw new Error(json.message || "Upload failed");
            }

        } catch (e) {
            console.error("Upload failed", e);
            status.textContent = "❌ Error: " + e.message;
            status.style.color = "#f87171";
        } finally {
            newBtn.disabled = false;
            newBtn.innerHTML = '<span>Upload Images</span><i data-lucide="upload-cloud"></i>';
            if (window.lucide) lucide.createIcons();
        }
    });

};

// --- End Init ---


function showDashboard() {
    document.getElementById('login-screen').classList.add('hidden');
    document.getElementById('admin-dashboard').classList.remove('hidden');
    loadData();
    initProductData(); // Load product details for modal
}


async function loadData() {
    try {
        // Get GAS URL
        const GAS_URL = "https://script.google.com/macros/s/AKfycbxL5HqRvV6REMAPtLdlRM6qcoVn42XwKse0YNU0xmLLy7O1iq7SzKMzjGZNNDnxXeQYDg/exec";

        // Populate the input if not already set, for product adds
        const urlInput = document.getElementById('google-script-url');
        if (urlInput && !urlInput.value) {
            urlInput.value = GAS_URL;
        }

        let orders = [];

        try {
            // First try GAS
            // Note: simple GET to GAS webapp (Anyone access) usually works fine.
            const res = await fetch(`${GAS_URL}?action=getOrders`);
            if (res.ok) {
                orders = await res.json();
            } else {
                throw new Error("GAS fetch failed");
            }
        } catch (e) {
            console.warn("Could not load from GAS, falling back to local/legacy", e);
            // Fallback to server if GAS fails or not provided
            try {
                const ordersRes = await fetch('/api/orders');
                orders = await ordersRes.json();
            } catch (ex) {
                console.error("Local fallback also failed", ex);
                orders = [];
            }
        }

        // 1. Visits
        let visitsData = { visits: 0, today: 0, history: {} };
        try {
            const visitsRes = await fetch('/api/visits');
            visitsData = await visitsRes.json();
            document.getElementById('stat-visits').textContent = visitsData.visits || 0;
            document.getElementById('stat-visits-today').textContent = visitsData.today || 0;
        } catch (e) {
            document.getElementById('stat-visits').textContent = '-';
            document.getElementById('stat-visits-today').textContent = '-';
        }

        document.getElementById('stat-orders').textContent = orders.length;

        // Initialize Dashboard Charts
        if (window.Chart) initDashboard(orders, visitsData);

        // 3. Revenue
        let revenue = 0;
        orders.forEach(o => {
            if (o.status === 'Closed') {
                const amt = parseFloat(o.total.replace(/[^\d.]/g, ''));
                if (!isNaN(amt)) revenue += amt;
            }
        });
        document.getElementById('stat-revenue').textContent = revenue.toFixed(3) + ' JOD';

        // 4. Render Activity Log (Last 5 events)
        const logBody = document.getElementById('activity-log');
        logBody.innerHTML = '';

        // Combine visits (mock timestamps?) and orders
        // For simplicity, just show recent orders in activity
        const recentOrders = [...orders].reverse().slice(0, 5);
        recentOrders.forEach(o => {
            const tr = document.createElement('tr');
            tr.innerHTML = `
                <td><span style="color:var(--success)">New Order</span></td>
                <td>${o.customerName} - ${o.total}</td>
                <td style="color:var(--text-secondary); font-size:0.85rem">${new Date(o.date).toLocaleTimeString()}</td>
            `;
            logBody.appendChild(tr);
        });

        // 5. Render Orders Table
        const ordersBody = document.getElementById('orders-table-body');
        ordersBody.innerHTML = '';
        [...orders].reverse().forEach(o => {
            const tr = document.createElement('tr');
            tr.className = 'order-row';
            const idStr = String(o.id);
            const rowId = `row-${o.id}`;
            const detailsId = `details-${o.id}`;

            tr.onclick = (e) => {
                // Ignore if clicked on select
                if (e.target.tagName === 'SELECT') return;
                toggleDetails(detailsId);
            };

            tr.innerHTML = `
                <td style="font-family:monospace">#${idStr.substr(0, 8)}</td>
                <td>${o.customerName}<br><span style="font-size:0.8em;color:grey">${o.customerPhone}</span></td>
                <td>${o.items ? o.items.length : 0} Items</td>
                <td>${o.total}</td>
                <td>${new Date(o.date).toLocaleDateString()}</td>
                <td>${renderStatusSelect(o.id, o.status || 'Placed')}</td>
            `;
            ordersBody.appendChild(tr);

            // Details Row
            const detailsTr = document.createElement('tr');
            detailsTr.id = detailsId;
            detailsTr.className = 'expanded-row hidden';

            let itemsHtml = '';
            if (o.items && Array.isArray(o.items)) {
                itemsHtml = o.items.map(itemStr => {
                    const i = parseItemString(itemStr);

                    // Image Logic
                    // Image Logic
                    let imgHtml = '';
                    if (window.DRIVE_MAPPING && window.DRIVE_MAPPING[i.sku]) {
                        const driveId = window.DRIVE_MAPPING[i.sku];
                        const imgSrc = `https://lh3.googleusercontent.com/d/${driveId}`;
                        imgHtml = `<img src="${imgSrc}" class="item-image" loading="lazy">`;
                    } else {
                        // Fallback checking using helper function
                        // Start with PNG
                        imgHtml = `<img src="assets/products/${i.sku}.png" class="item-image" loading="lazy" onerror="handleAdminImageError(this, '${i.sku}')">`;
                    }

                    // Sanitize SKU for HTML attribute
                    const safeSku = i.sku.replace(/"/g, '&quot;');

                    return `
                        <div class="item-tile" data-sku="${safeSku}" title="Click for Details" onclick="window.handleItemClick(this, event)">
                            ${imgHtml}
                            <div class="item-info">
                                <div class="item-header">
                                    <span class="item-sku">${i.sku}</span>
                                    <span class="item-qty">x${i.qty}</span>
                                </div>
                                <div class="item-name">${i.name}</div>
                                <div class="item-details">
                                    <span class="item-detail-badge" style="color:#94a3b8">
                                        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/></svg>
                                        ${i.color}
                                    </span>
                                    <span class="item-detail-badge" style="margin-left:auto; color:var(--success)">
                                        ${i.price} JOD
                                    </span>
                                </div>
                            </div>
                        </div>
                    `;
                }).join('');
            }

            // Extended Details Logic
            const infoSection = `
                <div class="order-info-grid">
                    <div class="info-group">
                        <label>Delivery Method</label>
                        <span>${o.method === 'pickup' ? 'Pickup' : 'Delivery'}</span>
                    </div>
                    ${o.method !== 'pickup' ? `
                    <div class="info-group">
                        <label>Region & Company</label>
                        <span>${o.selectedRegion || '-'} / ${o.selectedCompany || '-'}</span>
                    </div>
                    ` : ''}
                    <div class="info-group">
                        <label>Address</label>
                        <span>${o.address || '-'}</span>
                    </div>
                     <div class="info-group">
                        <label>Payment</label>
                        <span>${o.paymentMethod || '-'}</span>
                    </div>
                     <div class="info-group">
                        <label>Delivery Cost</label>
                        <span>${o.deliveryCost || '0.00'} JOD</span>
                    </div>
                </div>
            `;

            detailsTr.innerHTML = `
                <td colspan="6">
                    <div class="expanded-container">
                        <div class="items-grid">
                            ${itemsHtml}
                        </div>
                        ${infoSection}
                    </div>
                </td>
            `;
            ordersBody.appendChild(detailsTr);
        });

        // 6. Item Analytics
        const itemMap = {};
        orders.forEach(o => {
            o.items.forEach(item => {
                const qtyMatch = item.match(/\(Qty:\s*(\d+)\)/);
                const qty = qtyMatch ? parseInt(qtyMatch[1]) : 1;
                const nameMatch = item.match(/\[(.*?)\]/);
                const id = nameMatch ? nameMatch[1] : 'Unknown';
                const priceMatch = item.match(/-\s*(\d+\.\d+)\s*-/);
                const price = priceMatch ? parseFloat(priceMatch[1]) : 0;

                if (!itemMap[id]) {
                    itemMap[id] = { id: id, name: item.split('-').pop().split('(')[0].trim(), qty: 0, rev: 0 };
                }
                itemMap[id].qty += qty;
                itemMap[id].rev += (price * qty);
            });
        });

        const analyticsBody = document.getElementById('item-analytics-body');
        analyticsBody.innerHTML = '';
        Object.values(itemMap).sort((a, b) => b.qty - a.qty).forEach(i => {
            const tr = document.createElement('tr');
            let imgHtml = `<img src="assets/products/${i.id}.jpg" onerror="this.style.display='none'" style="width:50px; height:50px; object-fit:cover; border-radius:8px;">`;
            tr.innerHTML = `
                <td>${imgHtml}</td>
                <td style="font-family:monospace">${i.id}</td>
                <td>${i.name}</td>
                <td>${i.qty}</td>
                <td>${i.rev.toFixed(3)} JOD</td>
            `;
            analyticsBody.appendChild(tr);
        });

    } catch (e) {
        console.error("Admin: Failed to load data from server", e);
    }
}

// --- Dashboard Charts Logic ---
let revenueChartInstance = null;
let visitsChartInstance = null;
let topProductsChartInstance = null;
let regionChartInstance = null;
let paymentChartInstance = null;

function initDashboard(orders, visitsData) {
    if (!orders) orders = [];

    // 1. Process Data for Revenue Trend (Group by Date)
    const dateMap = {};
    orders.forEach(o => {
        let dateStr = 'Unknown';
        // Prefer timestamp (seconds)
        if (o.timestamp) {
            dateStr = new Date(o.timestamp * 1000).toLocaleDateString();
        } else if (o.date) {
            dateStr = new Date(o.date).toLocaleDateString();
        }

        // Clean Amount
        const amt = parseFloat(o.total.replace(/[^\d.]/g, ''));
        if (!isNaN(amt)) {
            if (!dateMap[dateStr]) dateMap[dateStr] = 0;
            dateMap[dateStr] += amt;
        }
    });

    // Visits Data Preparation
    const visitDates = Object.keys(visitsData?.history || {}).sort((a, b) => new Date(a) - new Date(b));
    const visitCounts = visitDates.map(d => visitsData.history[d]);

    if (visitDates.length > 0) {
        // Render Visits Chart
        const ctxVisits = document.getElementById('visitsChart');
        if (ctxVisits) {
            if (visitsChartInstance) visitsChartInstance.destroy();
            visitsChartInstance = new Chart(ctxVisits, {
                type: 'line',
                data: {
                    labels: visitDates,
                    datasets: [{
                        label: 'Visits',
                        data: visitCounts,
                        borderColor: '#f97316', // Orange
                        backgroundColor: 'rgba(249, 115, 22, 0.1)',
                        tension: 0.4,
                        fill: true
                    }]
                },
                options: {
                    responsive: true,
                    plugins: { legend: { display: false } },
                    scales: {
                        x: { grid: { color: '#2d2d35' }, ticks: { color: '#94a3b8' } },
                        y: { grid: { color: '#2d2d35' }, ticks: { color: '#94a3b8', beginAtZero: true, precision: 0 } }
                    }
                }
            });
        }
    }


    const sortedDates = Object.keys(dateMap).sort((a, b) => new Date(a) - new Date(b));
    const revenueData = sortedDates.map(d => dateMap[d]);

    // 2. Render Revenue Chart
    const ctxRev = document.getElementById('revenueChart');
    if (ctxRev) {
        if (revenueChartInstance) revenueChartInstance.destroy();
        revenueChartInstance = new Chart(ctxRev, {
            type: 'line',
            data: {
                labels: sortedDates,
                datasets: [{
                    label: 'Revenue (JOD)',
                    data: revenueData,
                    borderColor: '#6d28d9',
                    backgroundColor: 'rgba(109, 40, 217, 0.1)',
                    tension: 0.4,
                    fill: true
                }]
            },
            options: {
                responsive: true,
                plugins: { legend: { display: false } },
                scales: {
                    x: { grid: { color: '#2d2d35' }, ticks: { color: '#94a3b8' } },
                    y: { grid: { color: '#2d2d35' }, ticks: { color: '#94a3b8' } }
                }
            }
        });
    }

    // 3. Process Top Products
    const prodMap = {};
    orders.forEach(o => {
        if (o.items) {
            o.items.forEach(item => {
                // Try to extract simplified name
                // Format: "Name - Price - [ID] (Qty: X)" OR just string
                let name = item;
                let qty = 1;

                if (item.includes('[') && item.includes(']')) {
                    // Extract SKU from brackets [SKU]
                    // Format: "1. [TRND-1225-129] ..."
                    const skuMatch = item.match(/\[(.*?)\]/);
                    if (skuMatch) {
                        name = skuMatch[1]; // Use SKU as the name/key
                    }
                }

                // Extract Qty
                const qtyMatch = item.match(/\(Qty:\s*(\d+)\)/);
                if (qtyMatch) qty = parseInt(qtyMatch[1]);

                if (!prodMap[name]) prodMap[name] = 0;
                prodMap[name] += qty;
            });
        }
    });

    const sortedProds = Object.entries(prodMap).sort((a, b) => b[1] - a[1]).slice(0, 5);

    // 4. Render Top Products Chart
    const ctxProd = document.getElementById('topProductsChart');
    if (ctxProd) {
        if (topProductsChartInstance) topProductsChartInstance.destroy();
        topProductsChartInstance = new Chart(ctxProd, {
            type: 'bar',
            data: {
                labels: sortedProds.map(p => p[0]), // Show full SKU, no truncation
                datasets: [{
                    label: 'Units Sold',
                    data: sortedProds.map(p => p[1]),
                    backgroundColor: '#10b981',
                    borderRadius: 4
                }]
            },
            options: {
                responsive: true,
                plugins: { legend: { display: false } },
                scales: {
                    x: { grid: { display: false }, ticks: { color: '#94a3b8' } },
                    y: {
                        grid: { color: '#2d2d35' },
                        ticks: {
                            color: '#94a3b8',
                            precision: 0,
                            stepSize: 1
                        }
                    }
                }
            }
        });
    }

    // 5. Region Distribution
    const regionMap = {};
    orders.forEach(o => {
        let reg = o.selectedRegion;

        // Handle Pickup
        if (o.method === 'pickup') {
            reg = 'Pickup';
        }
        // Handle missing/empty region
        else if (!reg || reg.trim() === '') {
            reg = 'Unknown';
        }

        reg = reg.trim();
        if (!regionMap[reg]) regionMap[reg] = 0;
        regionMap[reg]++;
    });

    const ctxReg = document.getElementById('regionChart');
    if (ctxReg) {
        if (regionChartInstance) regionChartInstance.destroy();
        regionChartInstance = new Chart(ctxReg, {
            type: 'doughnut',
            data: {
                labels: Object.keys(regionMap),
                datasets: [{
                    data: Object.values(regionMap),
                    backgroundColor: ['#3b82f6', '#8b5cf6', '#ec4899', '#f59e0b', '#10b981'],
                    borderWidth: 0
                }]
            },
            options: {
                responsive: true,
                plugins: { legend: { position: 'right', labels: { color: '#94a3b8' } } }
            }
        });
    }

    // 6. Payment Methods
    const payMap = {};
    orders.forEach(o => {
        const method = o.paymentMethod || 'Cash On Delivery';
        if (!payMap[method]) payMap[method] = 0;
        payMap[method]++;
    });

    const ctxPay = document.getElementById('paymentChart');
    if (ctxPay) {
        if (paymentChartInstance) paymentChartInstance.destroy();
        paymentChartInstance = new Chart(ctxPay, {
            type: 'pie',
            data: {
                labels: Object.keys(payMap),
                datasets: [{
                    data: Object.values(payMap),
                    backgroundColor: ['#6366f1', '#14b8a6', '#f43f5e'],
                    borderWidth: 0
                }]
            },
            options: {
                responsive: true,
                plugins: { legend: { position: 'right', labels: { color: '#94a3b8' } } }
            }
        });
    }
}


// --- Order Status Logic ---
function renderStatusSelect(id, currentStatus) {
    const options = ['Placed', 'Preparing', 'Delivery', 'Not Paid', 'Closed', 'Canceled', 'Ignored'];
    const colorMap = {
        'Placed': '#3b82f6',     // Blue
        'Preparing': '#f59e0b',  // Orange
        'Delivery': '#8b5cf6',   // Purple
        'Not Paid': '#ec4899',   // Pink
        'Closed': '#10b981',     // Green
        'Canceled': '#ef4444',   // Red
        'Ignored': '#64748b'     // Gray
    };

    // Fallback for unknown status
    const color = colorMap[currentStatus] || '#3b82f6';

    let opts = options.map(opt => `<option value="${opt}" ${opt === currentStatus ? 'selected' : ''}>${opt}</option>`).join('');

    return `<select onchange="window.updateOrderStatus('${id}', this.value)" 
            style="background: ${color}20; color: ${color}; border: 1px solid ${color}; padding: 4px 8px; border-radius: 4px; cursor: pointer; font-weight: 500;">
            ${opts}
            </select>`;
}


window.updateOrderStatus = async function (id, newStatus) {
    try {
        const GAS_URL = "https://script.google.com/macros/s/AKfycbxL5HqRvV6REMAPtLdlRM6qcoVn42XwKse0YNU0xmLLy7O1iq7SzKMzjGZNNDnxXeQYDg/exec";

        if (GAS_URL) {
            // Update via GAS
            const payload = {
                action: 'updateStatus',
                orderId: id,
                status: newStatus
            };

            await fetch(GAS_URL, {
                method: 'POST',
                body: JSON.stringify(payload),
                headers: { "Content-Type": "text/plain;charset=utf-8" }
            });
            // We assume success or it fails silently/logs error. GAS return is hard to read due to no-cors/redirects sometimes.
            // But if we use redirect:follow, we might get it.

            // Reload to verify
            setTimeout(loadData, 1000);

        } else {
            // Fallback to local server
            const res = await fetch('/api/update-order-status', {
                method: 'POST',
                body: JSON.stringify({ orderId: id, status: newStatus })
            });
            const json = await res.json();
            if (json.status === 'success') {
                loadData();
            } else {
                alert("Failed to update status: " + (json.message || "Unknown error"));
            }
        }
    } catch (e) {
        console.error("Error updating status:", e);
        alert("Error updating status");
    }
}

function toggleDetails(id) {
    const el = document.getElementById(id);
    if (el) {
        if (el.classList.contains('hidden')) {
            el.classList.remove('hidden');
            el.classList.add('fade-in-up');
        } else {
            el.classList.add('hidden');
            el.classList.remove('fade-in-up');
        }
    }
}

function parseItemString(str) {
    let sku = 'N/A';
    let color = 'Default';
    let price = '0.00';
    let name = 'Item';
    let qty = 1;

    try {
        // 1. Extract and remove Quantity: "(Qty: 5)"
        const qtyMatch = str.match(/\(Qty:\s*(\d+)\)/);
        if (qtyMatch) {
            qty = qtyMatch[1];
            str = str.replace(qtyMatch[0], '').trim();
        }

        // 2. Strict Regex for format: "Index. [SKU] (Color) - Price - Name"
        // Escaped decimals for price, greedy match for name
        const match = str.match(/^\d+\.\s*\[(.*?)\]\s*\((.*?)\)\s*-\s*([\d.]+)\s*-\s*(.*)$/);

        if (match) {
            sku = match[1];
            color = match[2];
            price = match[3]; // Capture price group
            name = match[4];  // Capture name group (rest of string)
        } else {
            // Fallback: Use " - " (space dash space) as delimiter which is safer than "-"
            const parts = str.split(' - ');
            if (parts.length >= 3) {
                // parts[0]: "1. [TRND...-...] (Color)"
                // parts[1]: "13.08"
                // parts[2]: "Name"
                price = parts[1].trim();
                name = parts.slice(2).join(' - ').trim(); // Rejoin if name had separators

                // Extract SKU/Color from parts[0]
                const skuM = parts[0].match(/\[(.*?)\]/);
                if (skuM) sku = skuM[1];
                const colM = parts[0].match(/\((.*?)\)/);
                if (colM) color = colM[1];
            }
        }
    } catch (e) {
        console.warn("Error parsing item:", str, e);
        name = str;
    }

    return { sku, color, price, name, qty };
}

function handleAdminImageError(img, sku) {
    const currentSrc = img.src;

    // Check if it's a Drive URL or valid standard URL
    const isStandardAsset = currentSrc.includes('assets/products/');

    if (!isStandardAsset) {
        // If it was a Drive/Cloud URL and failed, fallback immediately to local PNG
        // The local fallback chain (PNG->JPG->etc) will take over if PNG fails
        img.src = `assets/products/${sku}.png`;
        return;
    }

    // Standard Fallback Chain for Local Assets
    if (currentSrc.endsWith('.png')) {
        img.src = `assets/products/${sku}.jpg`;
    } else if (currentSrc.endsWith('.jpg')) {
        img.src = `assets/products/${sku}.jpeg`;
    } else if (currentSrc.endsWith('.jpeg')) {
        img.src = `assets/products/${sku}.webp`;
    } else {
        // Final fallback: Placeholder
        img.onerror = null; // Stop infinite loop
        img.parentNode.innerHTML = '<div class="item-image" style="display:flex;align-items:center;justify-content:center;color:#64748b;font-size:0.8rem;background:rgba(0,0,0,0.2);">No Img</div>';
    }
}

// --- PRODUCT MODAL LOGIC & HELPERS ---

window.allProducts = [];
const PRODUCT_CSV_URL = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSTejg41yuaKcYa0CbOodUP9osmE5DIv8ZNQyMXlHJLLh2pQUZ5EoMT93UgV3LZfhAJcPEL8uEfK9Y4/pub?gid=897526080&single=true&output=csv';

async function initProductData() {
    if (window.allProducts && window.allProducts.length > 0) return; // Already loaded

    try {
        console.log("Fetching Product CSV from:", PRODUCT_CSV_URL);
        // Use Papa Parse directly via URL if possible, or fetch text first
        // Papa.parse supports remote files if 'download: true'
        Papa.parse(PRODUCT_CSV_URL, {
            download: true,
            header: true,
            skipEmptyLines: true,
            complete: (results) => {
                if (results.data) {
                    window.allProducts = results.data;
                    console.log("Products loaded:", window.allProducts.length);
                }
            },
            error: (err) => {
                console.error("Papa Parse Error:", err);
            }
        });
    } catch (e) {
        console.error("Failed to load products:", e);
    }
}

function extractDriveId(url) {
    if (!url) return null;
    let match = url.match(/\/(?:file\/)?d\/([a-zA-Z0-9_-]+)/);
    if (match) return match[1];
    match = url.match(/[?&]id=([a-zA-Z0-9_-]+)/);
    if (match) return match[1];
    if (url.length > 20 && /^[a-zA-Z0-9_-]+$/.test(url)) return url;
    return null;
}

// Minimal Translation Stub for Admin (English default)
const translations = {
    en: {
        retailPrice: "Retail Price",
        priceLabel: "Price",
        bulkSaving: "Wholesale Price (>10 pcs)",
        oos: "Out of Stock",
        inStock: "In Stock",
        copy: "Copy",
        viewDoc: "View Document",
        categoryLabel: "Category",
        collectionLabel: "Collection",
        dimensionsLabel: "Dimensions",
        targetMarketLabel: "Target Market",
        descriptionLabel: "Description",
        noDesc: "No description available.",
        selectColor: "Available Colors"
    }
};

window.getColorHex = function (name) {
    const colors = {
        'Black': '#1a1a1a',
        'White': '#ffffff',
        'Red': '#dc2626',
        'Blue': '#2563eb',
        'Green': '#16a34a',
        'Yellow': '#ca8a04',
        'Purple': '#9333ea',
        'Orange': '#ea580c',
        'Pink': '#db2777',
        'Gray': '#4b5563',
        'Brown': '#78350f',
        'Beige': '#f5f5dc',
        'Navy': '#1e3a8a',
        'Gold': '#d4af37',
        'Silver': '#94a3b8'
    };
    return colors[name] || '#e2e8f0';
};

window.handleItemClick = function (element, event) {
    if (event) {
        event.preventDefault();
        event.stopPropagation();
    }
    const sku = element.getAttribute('data-sku');
    console.log("handleItemClick called. SKU:", sku);
    if (sku) {
        window.toggleItemExpansion(element, sku);
    } else {
        console.error("handleItemClick: No SKU found on element", element);
    }
};

window.toggleItemExpansion = function (element, sku) {
    // Check if already expanded
    if (element.classList.contains('expanded')) {
        // Collapse
        element.classList.remove('expanded');
        const details = element.querySelector('.inline-details-container');
        if (details) details.remove();
        return;
    }

    // Collapse other expanded items in the same container (Accordion style - optional but cleaner)
    const siblings = element.parentNode.querySelectorAll('.item-tile.expanded');
    siblings.forEach(sib => {
        sib.classList.remove('expanded');
        const d = sib.querySelector('.inline-details-container');
        if (d) d.remove();
    });

    // Expand
    sku = String(sku).trim();
    if (!window.allProducts || window.allProducts.length === 0) {
        initProductData().then(() => {
            // Retry once after load
            window.toggleItemExpansion(element, sku);
        });
        return;
    }

    const productRaw = window.allProducts.find(p => {
        const no = p['No'] || p['Item Number'] || p['no'] || p['id'] || '';
        return String(no).trim().toLowerCase() === sku.toLowerCase();
    });

    if (!productRaw) {
        alert("Details not available for Item #" + sku);
        return;
    }

    const html = window.getProductDetailsHtml(productRaw, `window.toggleItemExpansion(this.closest('.item-tile'), '${p.no}')`);

    element.insertAdjacentHTML('beforeend', html);
    element.classList.add('expanded');

    // Re-init icons if any exist in the template (currently none, but good practice)
    if (window.lucide) lucide.createIcons();
};

window.getProductDetailsHtml = function (productRaw, closeJs) {
    // Normalize Data
    const sku = productRaw['No'] || productRaw['Item Number'] || productRaw['no'] || productRaw['id'] || '';
    const p = {
        name: productRaw['Name on Store'] || productRaw['Product Name'] || productRaw['product name'] || productRaw['Name'] || 'Unknown',
        no: sku,
        image: productRaw['Image'] || productRaw['image'] || productRaw['Photo'] || '',
        link: productRaw['Document Link'] || productRaw['link'] || '',
        price: productRaw['Price'] || productRaw['Retail Price'] || productRaw['Price < 25 QTY'] || '0',
        bulkPrice: productRaw['Wholesale Price'] || productRaw['Price > 25 QTY'] || '',
        category: productRaw['Category'] || productRaw['category'],
        collection: productRaw['Collection'] || productRaw['collection'],
        dimensions: productRaw['Dimensions'] || productRaw['Dimensions(mm) x y z'],
        targetMarket: productRaw['Target Market'] || productRaw['target market'],
        description: productRaw['Description'] || productRaw['description (80 word)'],
        colors: (productRaw['Colors'] || '').split(',').map(c => c.trim()).filter(c => c),
    };

    const t = translations.en;

    // Force Local Assets Only as requested
    // The handleAdminImageError function will handle extension fallback (png -> jpg -> etc)
    let imageSrc = `assets/products/${p.no}.png`;

    // Add a new property 'available' based on 'Stock' or 'Availability'
    p.available = productRaw['Stock'] || productRaw['Availability'] || 'Yes';

    return `
        <div class="inline-details-container" onclick="event.stopPropagation()" style="animation: fadeIn 0.3s ease-in-out;">
            <!-- Header -->
            <div class="premium-header">
                 <div style="display:flex; align-items:center; gap:1rem;">
                    <h1 class="premium-title">${p.name}</h1>
                    ${p.available === 'No' ? '<span style="background:#fee2e2; color:#ef4444; padding:0.2rem 0.6rem; border-radius:4px; font-weight:600; font-size:0.75rem; letter-spacing:0.05em;">OUT OF STOCK</span>' : ''}
                 </div>
                 <span class="premium-sku-badge">#${p.no}</span>
            </div>

            <!-- Content Grid -->
            <div class="premium-grid">
                <!-- Left: Image -->
                <div class="premium-image-container">
                    <img 
                        src="${imageSrc}" 
                        alt="${p.name}" 
                        class="premium-image"
                        onload="this.style.display='block'; this.onerror=null;"
                        onerror="if(window.handleAdminImageError) window.handleAdminImageError(this, '${p.no}')"
                    >
                </div>

                <!-- Right: Details -->
                <div class="premium-details">
                    
                    <div class="premium-data-grid">
                         <div class="premium-data-item">
                            <span class="premium-label">${t.categoryLabel}</span>
                            <span class="premium-value">${p.category || '-'}</span>
                         </div>
                         <div class="premium-data-item">
                            <span class="premium-label">${t.collectionLabel}</span>
                            <span class="premium-value">${p.collection || '-'}</span>
                         </div>
                         <div class="premium-data-item">
                            <span class="premium-label">${t.dimensionsLabel}</span>
                            <span class="premium-value">${p.dimensions || '-'}</span>
                         </div>
                         <div class="premium-data-item">
                            <span class="premium-label">${t.targetMarketLabel}</span>
                            <span class="premium-value">${p.targetMarket || '-'}</span>
                         </div>
                    </div>

                    <div class="premium-description">
                        <strong style="display:block; margin-bottom:0.5rem; color:var(--text-secondary); font-weight:700;">${t.descriptionLabel}</strong>
                        ${p.description || t.noDesc}
                    </div>

                    ${p.colors && p.colors.length > 0 ? `
                        <div class="premium-colors">
                            <div style="margin-bottom:0.5rem; font-size:0.75rem; text-transform:uppercase; color:#64748b; font-weight:600; letter-spacing:0.1em;">
                                ${t.selectColor}
                            </div>
                            <div>
                                ${p.colors.map(color => `
                                    <span class="premium-color-tag">${color}</span>
                                `).join('')}
                            </div>
                        </div>
                    ` : ''}

                    <div class="premium-footer">
                        <div class="premium-price-block">
                             <span class="premium-price-label">Price &lt; 25 QTY</span>
                             <span class="premium-price-value">${p.price} JOD</span>
                        </div>
                        <div class="premium-price-block">
                             <span class="premium-price-label" style="color:#b45309;">Price >= 25 QTY</span>
                             <span class="premium-price-value" style="color:#d97706;">${p.bulkPrice || '-'} JOD</span>
                        </div>
                    </div>

                </div>
            </div>
            
            <!-- Bottom Close Bar -->
            <div class="premium-close-bar" onclick="${closeJs}">
                Close Details
            </div>
        </div>
    `;
};

// --- Product List Logic ---
const CSV_URL = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSTejg41yuaKcYa0CbOodUP9osmE5DIv8ZNQyMXlHJLLh2pQUZ5EoMT93UgV3LZfhAJcPEL8uEfK9Y4/pub?gid=897526080&single=true&output=csv';

window.fetchProductsData = async function () {
    if (window.currentProducts && window.currentProducts.length > 0) {
        return window.currentProducts;
    }

    try {
        const res = await fetch(CSV_URL);
        const text = await res.text();
        return new Promise((resolve, reject) => {
            Papa.parse(text, {
                header: true,
                skipEmptyLines: true,
                complete: function (results) {
                    window.currentProducts = results.data;
                    resolve(results.data);
                },
                error: (err) => reject(err)
            });
        });
    } catch (e) {
        console.error("Error fetching CSV", e);
        return [];
    }
};

window.loadProducts = async function () {
    console.log("Loading products...");
    const tbody = document.getElementById('products-list-body');
    if (!tbody) return;
    tbody.innerHTML = '<tr><td colspan="7">Loading...</td></tr>';

    try {
        const data = await window.fetchProductsData();
        renderProductsTable(data);
    } catch (e) {
        console.error("Error loading products", e);
        tbody.innerHTML = '<tr><td colspan="7">Error loading products. Check console.</td></tr>';
    }
};

window.prepareAddProductForm = async function () {
    // Reset form to "Add" state
    const form = document.getElementById('add-product-form');
    if (!form) return;

    form.reset();
    document.getElementById('product-action').value = 'addProduct';
    document.getElementById('edit-product-no').value = '';
    document.getElementById('page-title').textContent = "Add Product";
    if (form.elements['No']) form.elements['No'].readOnly = false;

    const submitBtn = form.querySelector('button[type="submit"]');
    if (submitBtn) submitBtn.textContent = "Add Product";

    // Auto-increment logic
    try {
        const data = await window.fetchProductsData();
        const nextNo = getNextItemNumber(data);
        if (nextNo && form.elements['No']) {
            form.elements['No'].value = nextNo;
        }
    } catch (e) {
        console.error("Error auto-incrementing", e);
    }
};

window.getNextItemNumber = function (products) {
    if (!products || products.length === 0) return '';

    // Filter for valid IDs and find the last one (assuming order in CSV matters, or sort?)
    // Usually usage is sequential, so the last valid row with an ID is the latest.
    // Let's look at the last few entries.

    let lastId = '';
    for (let i = products.length - 1; i >= 0; i--) {
        if (products[i]['No'] && products[i]['No'].trim() !== '') {
            lastId = products[i]['No'];
            break;
        }
    }

    if (!lastId) return '';

    // Regex to separate prefix and number
    // Supports: "ABC-123", "Item10", "A-B-C-005"
    // Captures everything up to the last digit sequence as group 1, and the digits as group 2.
    const match = lastId.match(/^(.*?)(\d+)$/);

    if (match) {
        const prefix = match[1];
        const numberStr = match[2];
        const number = parseInt(numberStr, 10);
        const nextNumber = number + 1;

        // Pad with leading zeros to match original length
        const paddedNextNumber = String(nextNumber).padStart(numberStr.length, '0');

        return prefix + paddedNextNumber;
    }

    return lastId; // Fallback if no digits found
};

window.renderProductsTable = function (data) {
    const tbody = document.getElementById('products-list-body');
    tbody.innerHTML = '';

    if (data.length === 0) {
        tbody.innerHTML = '<tr><td colspan="7">No products found.</td></tr>';
        return;
    }

    data.forEach(row => {
        if (!row['No']) return;

        const tr = document.createElement('tr');
        let imgHtml = `<img src="assets/products/${row['No']}.jpg" onerror="this.style.display='none'" style="width:50px; height:50px; object-fit:cover; border-radius:8px;">`;

        const isActive = row['Available'] === 'TRUE';
        const statusHtml = isActive
            ? '<span class="status-badge status-active">Active</span>'
            : '<span class="status-badge status-inactive">Hidden</span>';

        tr.onclick = function () { window.toggleProductRowExpansion(this, row['No']); };
        tr.style.cursor = 'pointer';
        tr.className = 'product-row-item';

        tr.innerHTML = `
            <td>${imgHtml}</td>
            <td style="font-family:monospace; font-weight:600; font-size:0.9rem;">${row['No']}</td>
            <td style="font-weight:500;">${row['Name on Store'] || row['product name'] || '-'}</td>
            <td style="opacity:0.8;">${row['category']}</td>
            <td style="font-weight:700; color:#fff;">${row['Price < 25 QTY']}</td>
            <td>${statusHtml}</td>
            <td onclick="event.stopPropagation()">
                <div class="action-buttons">
                    <button class="btn-icon btn-edit" onclick="window.editProduct('${row['No']}')" title="Edit">
                        <i data-lucide="edit-2" style="width:16px; height:16px;"></i>
                    </button>
                    <button class="btn-icon btn-delete" onclick="window.deleteProduct('${row['No']}')" title="Delete">
                        <i data-lucide="trash-2" style="width:16px; height:16px;"></i>
                    </button>
                </div>
            </td>
        `;
        tbody.appendChild(tr);
    });

    // Initialize new icons
    if (window.lucide) lucide.createIcons();
};

window.toggleProductRowExpansion = function (tr, sku) {
    const nextRow = tr.nextElementSibling;
    if (nextRow && nextRow.classList.contains('product-expanded-row')) {
        nextRow.remove();
        tr.classList.remove('active-expanded');
        return;
    }

    // Collapse other expanded rows
    document.querySelectorAll('.product-expanded-row').forEach(row => row.remove());
    document.querySelectorAll('.product-row-item').forEach(row => row.classList.remove('active-expanded'));

    const product = window.currentProducts.find(p => p['No'] === sku);
    if (!product) return;

    tr.classList.add('active-expanded');

    const expandedTr = document.createElement('tr');
    expandedTr.className = 'product-expanded-row';

    // Use the shared HTML generator
    // The close action simply removes this row
    const html = window.getProductDetailsHtml(product, "this.closest('tr').remove(); document.querySelector('.product-row-item.active-expanded')?.classList.remove('active-expanded');");

    expandedTr.innerHTML = `
        <td colspan="7" style="padding: 0; background: #1e1e24; border-bottom: 1px solid var(--gold-500); border-top: 1px solid transparent;">
            ${html}
        </td>
    `;

    tr.after(expandedTr);

    // Animate
    setTimeout(() => expandedTr.style.opacity = '1', 10);
};

window.editProduct = function (no) {
    const product = window.currentProducts?.find(p => p['No'] === no);
    if (!product) { alert("Product not found. Please refresh."); return; }

    document.querySelector('.nav-item[data-view="add-product"]').click();

    document.getElementById('page-title').textContent = `Editing ${no}`;
    document.getElementById('product-action').value = 'updateProduct';
    document.getElementById('edit-product-no').value = no;

    const form = document.getElementById('add-product-form');
    if (form.elements['No']) { form.elements['No'].value = product['No']; form.elements['No'].readOnly = true; }
    if (form.elements['Name on Store']) form.elements['Name on Store'].value = product['Name on Store'] || product['product name'];
    if (form.elements['Arabic Name']) form.elements['Arabic Name'].value = product['Arabic Name'];
    if (form.elements['Price < 25 QTY']) form.elements['Price < 25 QTY'].value = product['Price < 25 QTY'];
    if (form.elements['category']) form.elements['category'].value = product['category'];
    if (form.elements['collection']) form.elements['collection'].value = product['collection'];
    if (form.elements['description (80 word)']) form.elements['description (80 word)'].value = product['description (80 word)'];
    if (form.elements['Colors']) form.elements['Colors'].value = product['Colors'];
    if (form.elements['Dimensions(mm) x y z']) form.elements['Dimensions(mm) x y z'].value = product['Dimensions(mm) x y z'];

    const btn = form.querySelector('button[type="submit"]');
    btn.innerText = "Update Product";
};

window.deleteProduct = async function (no) {
    if (!confirm(`Are you sure you want to delete ${no}?`)) return;
    const url = document.getElementById('google-script-url').value;
    if (!window.submitToGas) { alert("Function not ready."); return; }

    await window.submitToGas(url, { action: 'deleteProduct', No: no });
    setTimeout(loadProducts, 2000); // Refresh after delay
};

// --- Initialization Logic for GAS URL ---
window.checkGasUrlVisibility = function () {
    const input = document.getElementById('google-script-url');
    const container = document.getElementById('gas-url-container');

    if (input && container) {
        if (input.value && input.value.trim() !== '') {
            container.style.display = 'none';
        } else {
            container.style.display = 'block';
        }
    }
};

// Run after a short delay to ensure value is populated if it comes from extensions/autofill
setTimeout(window.checkGasUrlVisibility, 100);


// --- Advanced Search & Sort Logic ---

window.currentSearchTerm = '';
window.currentSortColumn = '';
window.currentSortDirection = 'asc';

window.handleProductSearch = function (term) {
    window.currentSearchTerm = term.toLowerCase();
    window.filterAndRenderProducts();
};

window.handleSort = function (column) {
    if (window.currentSortColumn === column) {
        // Toggle direction
        window.currentSortDirection = window.currentSortDirection === 'asc' ? 'desc' : 'asc';
    } else {
        window.currentSortColumn = column;
        window.currentSortDirection = 'asc';
    }
    window.filterAndRenderProducts();
};

// --- Smart Search Logic ---
window.levenshtein = function (a, b) {
    if (a.length === 0) return b.length;
    if (b.length === 0) return a.length;

    const matrix = [];
    for (let i = 0; i <= b.length; i++) {
        matrix[i] = [i];
    }
    for (let j = 0; j <= a.length; j++) {
        matrix[0][j] = j;
    }

    for (let i = 1; i <= b.length; i++) {
        for (let j = 1; j <= a.length; j++) {
            if (b.charAt(i - 1) === a.charAt(j - 1)) {
                matrix[i][j] = matrix[i - 1][j - 1];
            } else {
                matrix[i][j] = Math.min(
                    matrix[i - 1][j - 1] + 1, // substitution
                    Math.min(
                        matrix[i][j - 1] + 1, // insertion
                        matrix[i - 1][j] + 1  // deletion
                    )
                );
            }
        }
    }
    return matrix[b.length][a.length];
};

window.filterAndRenderProducts = function () {
    let products = [...window.currentProducts]; // Clone original list
    const term = window.currentSearchTerm;

    // 1. Filter (Smart Search)
    if (term && term.length > 0) {
        products = products.filter(p => {
            // Check ALL fields
            return Object.values(p).some(val => {
                const strVal = String(val).toLowerCase();

                // 1. Direct Include
                if (strVal.includes(term)) return true;

                // 2. Fuzzy Match (only if search term is > 2 chars)
                if (term.length > 2) {
                    // Allow 1 error for 3-5 chars, 2 errors for 6+ chars
                    const maxDist = term.length > 5 ? 2 : 1;

                    // Optimization: Only run expensive levenshtein if lengths are close
                    if (Math.abs(strVal.length - term.length) > maxDist + 2) return false;

                    // Check full value fuzzy
                    if (window.levenshtein(strVal, term) <= maxDist) return true;

                    // Also check individual words in the value
                    const words = strVal.split(/[\s-_]+/);
                    return words.some(w => window.levenshtein(w, term) <= maxDist);
                }
                return false;
            });
        });
    }

    // 2. Sort
    if (window.currentSortColumn) {
        products.sort((a, b) => {
            let valA = a[window.currentSortColumn] || '';
            let valB = b[window.currentSortColumn] || '';

            // Smart numeric sort
            const numA = parseFloat(valA);
            const numB = parseFloat(valB);

            // If both are numbers, compare numerically
            // "Price" fields usually are numbers
            if (!isNaN(numA) && !isNaN(numB) && window.currentSortColumn.includes('Price')) {
                return window.currentSortDirection === 'asc' ? numA - numB : numB - numA;
            }

            // String compare
            valA = String(valA).toLowerCase();
            valB = String(valB).toLowerCase();

            if (valA < valB) return window.currentSortDirection === 'asc' ? -1 : 1;
            if (valA > valB) return window.currentSortDirection === 'asc' ? 1 : -1;
            return 0;
        });
    }

    // 3. Render
    window.renderProductsTable(products);
    window.updateSortIcons();
};

window.updateSortIcons = function () {
    // Reset all headers
    document.querySelectorAll('.sortable-header').forEach(th => {
        th.classList.remove('asc', 'desc');
        const icon = th.querySelector('.sort-icon');
        if (icon) {
            // Reset icon (optional logic if we want to change icon type)
            // lucide.createIcons() handles basic rendering, CSS handles rotation
        }
    });

    // Set active header
    if (window.currentSortColumn) {
        // Find the header by onclick attribute to be safe or add data attributes
        // Simple search by onclick text
        const headers = Array.from(document.querySelectorAll('.sortable-header'));
        const activeHeader = headers.find(th => th.getAttribute('onclick').includes(`'${window.currentSortColumn}'`));

        if (activeHeader) {
            activeHeader.classList.add(window.currentSortDirection);
        }
    }
};
// --- MANUAL ORDER LOGIC ---

let manualCart = [];
let manualProducts = [];
let deliveryRegionsCache = {}; // { RegionName: { CompanyName: Price, ... } }

async function initCreateOrder() {
    console.log("Initializing Manual Order View...");
    manualCart = [];
    renderManualCart();

    // 1. Load Products (if not already loaded)
    if (manualProducts.length === 0) {
        await loadManualProducts();
    }

    // 2. Load Delivery Details
    await loadDeliveryDetails();

    // 3. Listeners
    document.getElementById('mo-product-search').addEventListener('input', handleProductSearch);
    document.getElementById('mo-add-btn').onclick = addToManualCart;
    document.getElementById('mo-create-btn').onclick = submitManualOrder;
    document.getElementById('mo-region').onchange = updateManualDeliveryOptions;
    // document.getElementById('mo-company').onchange = updateManualTotal; // Removed as element no longer exists
}

async function loadManualProducts() {
    const CSV_URL = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSTejg41yuaKcYa0CbOodUP9osmE5DIv8ZNQyMXlHJLLh2pQUZ5EoMT93UgV3LZfhAJcPEL8uEfK9Y4/pub?gid=897526080&single=true&output=csv';
    try {
        const res = await fetch(CSV_URL);
        const text = await res.text();

        Papa.parse(text, {
            header: true,
            skipEmptyLines: true,
            complete: (results) => {
                const data = results.data;
                // Normalize keys logic simplified from app.js
                const keys = Object.keys(data[0] || {});
                const productKey = keys.find(k => k.toLowerCase().includes('name on store')) || keys.find(k => k.toLowerCase().includes('product name'));
                const priceKey = keys.find(k => k.toLowerCase().includes('price') && k.includes('<'));
                const idKey = keys.find(k => k.toLowerCase().includes('no'));
                const imgKey = keys.find(k => k.toLowerCase().includes('image'));

                manualProducts = data.map(item => ({
                    name: item[productKey] || 'Unknown',
                    price: parseFloat((item[priceKey] || '0').replace(/[^\d.]/g, '')),
                    id: item[idKey] || 'N/A',
                    image: item[imgKey]
                })).filter(p => !isNaN(p.price));

                console.log(`Manual Order: Loaded ${manualProducts.length} products.`);
                // populateProductDatalist(); // Removed
            }
        });
    } catch (e) {
        console.error("Failed to load products for manual order", e);
    }
}

// function populateProductDatalist() { ... } // Removed

async function loadDeliveryDetails() {
    try {
        const res = await fetch('deliveryCompanies.json');
        const companies = await res.json();

        deliveryRegionsCache = {};

        companies.forEach(comp => {
            const companyName = comp.Name;
            const regions = comp.Regions;

            for (const [regionName, price] of Object.entries(regions)) {
                if (!deliveryRegionsCache[regionName]) {
                    deliveryRegionsCache[regionName] = {};
                }
                deliveryRegionsCache[regionName][companyName] = price;
            }
        });

        // Populate Region Select
        const regionSelect = document.getElementById('mo-region');
        regionSelect.innerHTML = '<option value="">-- Select Region --</option>' +
            Object.keys(deliveryRegionsCache).sort().map(r => `<option value="${r}">${r}</option>`).join('');

        console.log("Delivery details loaded from JSON.");

    } catch (e) {
        console.error("Failed to load delivery details", e);
    }
}

function updateManualDeliveryOptions() {
    const region = document.getElementById('mo-region').value;
    const listContainer = document.getElementById('mo-delivery-list');
    const companyInput = document.getElementById('mo-company-input');

    listContainer.innerHTML = '';
    companyInput.value = '';

    if (!region || !deliveryRegionsCache[region]) {
        listContainer.innerHTML = '<div style="text-align:center; color:var(--text-secondary); padding:1rem;">Select a region to see options</div>';
        updateManualTotal();
        return;
    }

    const companies = deliveryRegionsCache[region];

    // Sort companies by price ascending? or Keep original order?
    // Let's sort by price for better UX
    const sortedEntries = Object.entries(companies).sort((a, b) => a[1] - b[1]);

    sortedEntries.forEach(([comp, price]) => {
        const card = document.createElement('div');
        card.className = 'delivery-option-card';
        card.dataset.name = comp;
        card.dataset.price = price;

        card.innerHTML = `
            <span class="delivery-company-name">${comp}</span>
            <span class="delivery-company-price">${price.toFixed(2)} JOD</span>
        `;

        card.onclick = () => {
            // Deselect others
            document.querySelectorAll('.delivery-option-card').forEach(c => c.classList.remove('selected'));
            // Select this
            card.classList.add('selected');

            // Update Input
            companyInput.value = comp;

            updateManualTotal();
        };

        listContainer.appendChild(card);
    });

    updateManualTotal();
}


window.toggleManualDelivery = function (isDelivery) {
    const deliveryGroup = document.getElementById('mo-delivery-group');

    if (isDelivery) {
        deliveryGroup.style.display = 'block';
    } else {
        deliveryGroup.style.display = 'none';
        // Reset selection
        document.querySelectorAll('.delivery-option-card').forEach(c => c.classList.remove('selected'));
        document.getElementById('mo-company-input').value = "";
    }
    updateManualTotal();
}

function updateManualTotal() {
    const subtotal = manualCart.reduce((sum, item) => sum + (item.price * item.qty), 0);

    let delivery = 0;
    const isDelivery = document.querySelector('input[name="mo-method"]:checked').value === 'delivery';

    if (isDelivery) {
        const selectedCard = document.querySelector('.delivery-option-card.selected');
        if (selectedCard) {
            delivery = parseFloat(selectedCard.dataset.price);
        }
    }

    document.getElementById('mo-subtotal').textContent = subtotal.toFixed(3) + ' JOD';
    document.getElementById('mo-delivery').textContent = delivery.toFixed(3) + ' JOD';
    document.getElementById('mo-total').textContent = (subtotal + delivery).toFixed(3) + ' JOD';
}

async function submitManualOrder() {
    const name = document.getElementById('mo-name').value;
    const phone = document.getElementById('mo-phone').value;
    const region = document.getElementById('mo-region').value;
    const address = document.getElementById('mo-address').value;
    const payment = document.getElementById('mo-payment').value;

    // Check method
    const isDelivery = document.querySelector('input[name="mo-method"]:checked').value === 'delivery';
    const company = document.getElementById('mo-company-input').value; // Get from hidden input

    const msgEl = document.getElementById('mo-msg');
    const errEl = document.getElementById('mo-error');
    msgEl.classList.add('hidden');
    errEl.classList.add('hidden');

    // Validation
    if (!name || manualCart.length === 0) {
        errEl.textContent = "Please fill in customer name and add items.";
        errEl.classList.remove('hidden');
        return;
    }

    if (isDelivery && (!region || !company)) {
        errEl.textContent = "Please select a region and a delivery company.";
        errEl.classList.remove('hidden');
        return;
    }

    const totalText = document.getElementById('mo-total').textContent;

    const order = {
        id: 'MAN-' + Date.now(),
        customerName: name,
        customerPhone: phone || "N/A",
        selectedRegion: region || "N/A",
        selectedCompany: isDelivery ? company : "Pickup",
        address: address || "N/A",
        items: manualCart.map((item, idx) => {
            return `${idx + 1}. [${item.id}] (Default) - ${item.price.toFixed(3)} - ${item.name} (Qty: ${item.qty})`;
        }),
        total: totalText,
        method: isDelivery ? 'delivery' : 'pickup',
        paymentMethod: payment,
        status: 'Pending',
        timestamp: Date.now() / 1000,
        date: new Date().toISOString()
    };

    try {
        const res = await fetch('/api/orders', {
            method: 'POST',
            body: JSON.stringify(order)
        });
        const json = await res.json();

        if (json.status === 'success') {
            msgEl.textContent = "Order created successfully!";
            msgEl.classList.remove('hidden');
            // Clear Form
            manualCart = [];
            document.getElementById('mo-name').value = '';
            document.getElementById('mo-phone').value = '';
            document.getElementById('mo-address').value = '';
            document.getElementById('mo-company-input').value = '';
            const listContainer = document.getElementById('mo-delivery-list');
            if (listContainer) listContainer.innerHTML = '<div style="text-align:center; color:var(--text-secondary); padding:1rem;">Select a region first</div>';

            renderManualCart();
            // Redirect after 1s
            setTimeout(() => {
                document.querySelector('.nav-item[data-view="orders"]').click();
                loadData();
            }, 1000);
        } else {
            throw new Error(json.error || "Unknown error");
        }
    } catch (e) {
        errEl.textContent = "Error creating order: " + e.message;
        errEl.classList.remove('hidden');
    }
}
